Repository Eistbaren/client, pull requests merged in 2022-07, with the labels that each got.

#64 Feat: implement server connection of table page
  src/components/ReservationTimeslotTimePicker.tsx
  src/components/RestaurantCard.tsx
  src/components/RestaurantComment.tsx
  src/components/RestaurantDetailsModal.tsx
  src/components/TimeslotText.tsx
  src/data/Context.tsx
  src/data/PaginatedApi.tsx
  src/pages/Landingpage.tsx
  src/pages/SearchPage.tsx
  src/pages/TableSelectionPage.tsx
  src/utils/ContextWrapper.tsx
  src/utils/LocalizationProviderWrapper.tsx
Labels: enhancement

#83 Chore: context cleanup
  src/components/QueryTimeslotTimePicker.tsx
  src/components/RestaurantCard.tsx
  src/data/Context.tsx
  src/data/Query.tsx
  src/data/index.ts
  src/pages/Landingpage.tsx
  src/pages/PersonalData.tsx
  src/pages/ReservationDetails.tsx
  src/pages/TableSelectionPage.tsx
  src/utils/ContextWrapper.tsx
Labels: enhancement

#86 Fix: Content-Type Header
  src/data/api.ts
Labels: bug

#84 Feat: Reservation Details Page
  package-lock.json
  package.json
  src/css/ReservationDetails.css
  src/data/Context.tsx
  src/pages/ReservationDetails.tsx
  src/utils/ContextWrapper.tsx
Labels: enhancement

#85 Feat/personal data page server
  src/components/QueryTimeslotTimePicker.tsx
  src/pages/Landingpage.tsx
  src/pages/PersonalData.tsx
  src/pages/TableSelectionPage.tsx
  src/utils/ContextWrapper.tsx
Labels: enhancement

#99 🚀 Feat: details page redesign
  src/components/RestaurantCardSideways.tsx
  src/css/ReservationDetails.css
  src/pages/ReservationDetails.tsx
  src/utils/Theme.tsx
Labels: enhancement

#104 Feat: disable tables with not enough seats
  src/pages/TableSelectionPage.tsx
Labels: enhancement

#110 Feat: Show search indication when waiting for input
  src/pages/SearchPage.tsx
Labels: enhancement

#111 Feat: Add imprint modal
  src/components/FloatingSidebar.tsx
  src/components/ImprintModal.tsx
  src/css/Landingpage.css
  src/pages/Landingpage.tsx
Labels: enhancement

#113 Feat: Add google maps link
  src/components/RestaurantDetailsModal.tsx
Labels: enhancement

#114 Fix: Contrast on Resertvation Details Page
  src/pages/PersonalData.tsx
  src/pages/ReservationDetails.tsx
Labels: bug

#118 Fix: numberVisitors filter
  src/data/Query.tsx
  src/pages/Landingpage.tsx
  src/pages/SearchPage.tsx
  src/pages/TableSelectionPage.tsx
  src/utils/ContextWrapper.tsx
Labels: bug

#116 Feat: better confirmation dialog
  src/pages/ReservationDetails.tsx
Labels: enhancement

#123 Fix: rename ics file to add to calendar
  src/pages/ReservationDetails.tsx
Labels: enhancement

#124 Fix: add autofocus
  src/pages/PersonalData.tsx
Labels: bug

#115 🪲 Fix: Catch times under 12h in the future
  src/components/QueryTimeslotTimePicker.tsx
  src/css/Landingpage.css
  src/pages/Landingpage.tsx
  src/pages/TableSelectionPage.tsx
  src/utils/ContextWrapper.tsx
Labels: bug, enhancement

#127 🏎 Feat: Add ability to navigate with header
  src/components/Header.tsx
Labels: enhancement

#128 Fix: Update meta description
  public/index.html
Labels: enhancement

#130 Fix: #129
  src/pages/TableSelectionPage.tsx
Labels: bug

#133 Fix: Timepicker error messages
  src/components/QueryTimeslotTimePicker.tsx
  src/pages/Landingpage.tsx
  src/pages/TableSelectionPage.tsx
Labels: bug

#135 Fix: Set seconds to 0
  src/components/QueryTimeslotTimePicker.tsx
Labels: bug
